### ISSUE TITLE
Can we specify "encoding=utf8" ?

### ISSUE THREAD

**Issue by cxwithyxy** [edmundpf/file_tools#1]
```
(venv) M:\Wechat_SDK>python index.py
Traceback (most recent call last):
  File "index.py", line 12, in <module>
    script_string = get_file_string("frida_scripts/resv_msg.js")
  File "M:\Wechat_SDK\venv\lib\site-packages\file_tools\file.py", line 7, in get_file_string
    return f.read()
UnicodeDecodeError: 'gbk' codec can't decode byte 0xad in position 15: illegal multibyte sequence
```

**Comment by edmundpf** [comment]
Just saw this and merged the changes
